test:
  service: S3
  access_key_id: "AKIAYAANLLSNOPK3RUEN"
  secret_access_key: "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"
  region: us-east-2
  bucket: aulapos

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

amazon:
  service: S3
  access_key_id: "AKIAYAANLLSNOPK3RUEN"
  secret_access_key: "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"
  region: us-east-2
  bucket: aulapos